/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDataPointRegistry } from "./IDataPointRegistry";
export type { IDataPointStorage } from "./IDataPointStorage";
export type { IOwnable } from "./IOwnable";
