/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ColourMeNFT__factory } from "./ColourMeNFT__factory";
export { IColourMeNFT__factory } from "./IColourMeNFT__factory";
