/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as colourMeNftSol from "./ColourMeNFT.sol";
export type { colourMeNftSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ColourMeRenderer } from "./ColourMeRenderer";
