/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as colourMeNftSol from "./ColourMeNFT.sol";
export * as interfaces from "./interfaces";
export * as test from "./test";
export { ColourMeRenderer__factory } from "./ColourMeRenderer__factory";
