/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as extensions from "./extensions";
export { BaseWTTPPermissions__factory } from "./BaseWTTPPermissions__factory";
